#!/bin/bash
# Generate the Lean modules of one second-order certificate run for the kernel checks of
# Robbins/Cert/SO/EvalK.lean, Robbins/Cert/SO/Lanes.lean and Robbins/Cert/SO/LanesWin.lean (Section 6.1 of the
# paper), not committed (about 330 MB for the run of the paper), under OUT/RobbinsSO/NAME/:
#   Grid.lean                       the grid of the run (code/so-pack, mode grid)
#   Data/T0001.lean ... TNNNN.lean  the claimed tables of soq (code/soq, option emitall), one per time
#                                   (code/so-pack, mode table)
#   Step/SNNNN.lean                 checkLast on the table of time n
#   Step/Stttt_cc.lean              for a step t < n whose window changes: checkRange on the literals [lo, hi) of the
#                                   table of time t, the ranges covering its literals (the last one ends at the
#                                   length of the table)
#   Step/Stttt_Lcc.lean             for a fixed-window step t < n (start[t] = start[t+1]) with 3 | m + 1: lanesRange
#                                   on the top records [lo, hi), the ranges covering the records (the last one ends
#                                   at the number of records cnt_t + 1)
#   Step/Stttt_Wcc.lean             with LANES_WIN: lanesWin on the lanes [a, a + w) of the top record j, the
#                                   windows of a top covering its lanes, in place of a range of that top
#   Chain.lean, Final.lean          when every step is generated: the step theorems Ctttt (checkStep) from their
#                                   ranges, ChainSO of the tables (chain), the bound le_v and the relaxed
#                                   sub-solution relaxed (Robbins/Cert/SO/RunMain.lean), value read from table-1.txt
#   steps.txt                       one line per range: `t lo hi module` (literals), `t lo hi module tops` (top
#                                   records), `t j a module win w` (window), `n 0 0 module` for time n
# A file whose content is unchanged is not rewritten, so that Lake keeps its .olean.
# TABLES is a directory written by soq emitall=TABLES (code/soq/run.sh): grid.txt and table-T.txt.
# STEPS: `nonfixed` (default: the steps t whose window changes, and time n), `fixed` (the fixed-window steps, and
# time n), `all`, or a list of times. Literal ranges: the literals of the states whose last coordinate is a point of
# G_t in ranges of CHUNK_A literals (default 60), the others (last coordinate the point 1, the record lists of
# section 6) in ranges of CHUNK_B (default 20). Top ranges: consecutive tops while their states (C (j + m - 1, m - 1)
# for the top j) add up to at most LANES_STATES (default 2002), a top above it alone. LANES_WIN (default 1020, 0
# for none): a top of more than LANES_WIN lanes is cut into windows of at most LANES_WIN lanes, of near-equal
# sizes, and every fixed-window step of the chain is then joined by checkStep_of_lanesParts. SCALAR=1: every step
# by checkRange.
# The defaults are the settings of the run of the paper: code/formal-proof/gen.sh N300 TABLES . all, from the root
# of the package. Build with Lake (code/formal-proof/clean_build.sh).
# Usage: code/formal-proof/gen.sh NAME TABLES OUT [STEPS...]
set -euo pipefail
[ $# -ge 3 ] || { sed -n '/^# Usage/p' "$0" >&2; exit 2; }
name=$1; tables=$(cd "$2" && pwd); out=$3; shift 3
steps=${*:-nonfixed}
A=${CHUNK_A:-60}; B=${CHUNK_B:-20}; SL=${LANES_STATES:-2002}; WN=${LANES_WIN:-1020}
here=$(cd "$(dirname "$0")" && pwd)
pkg=$(cd "$here/../.." && pwd)
mkdir -p "$out"; out=$(cd "$out" && pwd)
run="$out/RobbinsSO/$name"
ns="RobbinsSO.$name"
tgt=$(mktemp -d); trap 'rm -rf "$tgt"' EXIT
(cd "$pkg/code/so-pack" && CARGO_TARGET_DIR="$tgt" cargo build --release --offline -q)
pack="$tgt/release/robbins-so-pack"
read -r n m sh K J < <(grep -v '^#' "$tables/grid.txt" | sed -n 1p)
mapfile -t start < <(grep -v '^#' "$tables/grid.txt" | sed -n 3p | tr ' ' '\n')
[ "${#start[@]}" = "$n" ] || { echo "gen.sh: $n start values expected" >&2; exit 1; }
p4() { printf '%04d' "$1"; }
cnt() { local s=${start[$(($1 - 1))]} a b; a=$((s < J ? s : J)); b=$((s + K < J ? s + K : J)); echo $((b - a)); }
binom() { local a=$1 b=$2 r=1 i; for ((i = 1; i <= b; i++)); do r=$((r * (a - b + i) / i)); done; echo $r; }
put() { # FILE: stdin into FILE, unless FILE already holds it
  cat > "$tgt/put"; cmp -s "$tgt/put" "$1" || mv "$tgt/put" "$1"
}
fixed() { [ "${start[$(($1 - 1))]}" = "${start[$1]}" ]; }
mkdir -p "$run/Data" "$run/Step"
"$pack" grid "$tables/grid.txt" "$ns" "$tgt/Grid.lean" > /dev/null
sed '/^import /a\
\
/-! The grid of the run (generated by code/formal-proof/gen.sh). -/' "$tgt/Grid.lean" | put "$run/Grid.lean"
for ((t = 1; t <= n; t++)); do
  "$pack" table "$tables/table-$t.txt" "$m" "$ns.Data" "T$(p4 "$t")" "$tgt/T.lean" > /dev/null
  put "$run/Data/T$(p4 "$t").lean" < "$tgt/T.lean"
done
want() { # T: is the step T generated
  case " $steps " in
    *" all "*) return 0 ;;
    *" nonfixed "*" fixed "* | *" fixed "*" nonfixed "*) return 0 ;;
    *" nonfixed "*) [ "$1" = "$n" ] || ! fixed "$1" ;;
    *" fixed "*) [ "$1" = "$n" ] || fixed "$1" ;;
    *) case " $steps " in *" $1 "*) return 0 ;; esac; return 1 ;;
  esac
}
: > "$run/steps.txt"
for ((t = 1; t < n; t++)); do
  want "$t" || continue
  a=$(p4 "$t"); b=$(p4 $((t + 1)))
  if fixed "$t" && [ $(((m + 1) % 3)) = 0 ] && [ "${SCALAR:-0}" != 1 ]; then
    R=$(($(cnt "$t") + 1))
    parts=(); s=0; lo=0
    for ((j = 0; j < R; j++)); do
      x=$(binom $((j + m - 1)) $((m - 1)))
      if [ "$WN" -gt 0 ] && [ "$x" -gt "$WN" ]; then
        [ "$j" -gt "$lo" ] && parts+=("$lo $j")
        k=$(((x + WN - 1) / WN)); o=0
        for ((q = 1; q <= k; q++)); do w=$((x * q / k - o)); parts+=("$j $o $w"); o=$((o + w)); done
        lo=$((j + 1)); s=0; continue
      fi
      if [ "$s" -gt 0 ] && [ $((s + x)) -gt "$SL" ]; then parts+=("$lo $j"); lo=$j; s=0; fi
      s=$((s + x))
    done
    [ "$R" -gt "$lo" ] && parts+=("$lo $R")
    for ((i = 0; i < ${#parts[@]}; i++)); do
      set -- ${parts[$i]}
      if [ $# = 3 ]; then
        mod=$(printf 'S%s_W%02d' "$a" "$i")
        put "$run/Step/$mod.lean" <<EOT
import Robbins.Cert.SO.LanesWin
import $ns.Grid
import $ns.Data.T$a
import $ns.Data.T$b

/-! The step $t of the run $name, lanes [$2, $(($2 + $3))) of the top record $1 (generated by code/formal-proof/gen.sh). -/

namespace $ns

theorem $mod : Robbins.Cert.SO.L.lanesWin grid $t Data.T$b Data.T$a $1 $2 $3 = true := by
  decide +kernel

end $ns
EOT
        echo "$t $1 $2 $mod win $3" >> "$run/steps.txt"
        continue
      fi
      lo=$1; hi=$2; mod=$(printf 'S%s_L%02d' "$a" "$i")
      put "$run/Step/$mod.lean" <<EOT
import Robbins.Cert.SO.Lanes
import $ns.Grid
import $ns.Data.T$a
import $ns.Data.T$b

/-! The step $t of the run $name, top records [$lo, $hi) in packed lanes (generated by code/formal-proof/gen.sh). -/

namespace $ns

theorem $mod : Robbins.Cert.SO.L.lanesRange grid $t Data.T$b Data.T$a $lo $hi = true := by
  decide +kernel

end $ns
EOT
      echo "$t $lo $hi $mod tops" >> "$run/steps.txt"
    done
    continue
  fi
  S=$(grep -v '^#' "$tables/table-$t.txt" | sed -n 1p)
  c=$(cnt "$t")
  NL=$(((S + 15) / 16))
  v=$(((S - $(binom $((c + m - 1)) $((m - 1)))) / 16))
  cuts=(); for ((x = 0; x < v; x += A)); do cuts+=("$x"); done
  for ((x = v; x < NL; x += B)); do cuts+=("$x"); done
  for ((i = 0; i < ${#cuts[@]}; i++)); do
    lo=${cuts[$i]}; mod=$(printf 'S%s_%02d' "$a" "$i")
    if [ $((i + 1)) -lt ${#cuts[@]} ]; then hi=${cuts[$((i + 1))]}; hiL=$hi; else hi=$NL; hiL="Data.T$a.length"; fi
    put "$run/Step/$mod.lean" <<EOT
import Robbins.Cert.SO.EvalK
import $ns.Grid
import $ns.Data.T$a
import $ns.Data.T$b

/-! The step $t of the run $name, literals [$lo, $hi) of the table of time $t (generated by code/formal-proof/gen.sh). -/

namespace $ns

theorem $mod : Robbins.Cert.SO.K.checkRange grid $t Data.T$b Data.T$a $lo ($hiL) = true := by
  decide +kernel

end $ns
EOT
    echo "$t $lo $hi $mod" >> "$run/steps.txt"
  done
done
a=$(p4 "$n")
put "$run/Step/S$a.lean" <<EOT
import Robbins.Cert.SO.EvalK
import $ns.Grid
import $ns.Data.T$a

/-! The table of time $n of the run $name (generated by code/formal-proof/gen.sh). -/

namespace $ns

theorem S$a : Robbins.Cert.SO.K.checkLast grid Data.T$a = true := by
  decide +kernel

end $ns
EOT
echo "$n 0 0 S$a" >> "$run/steps.txt"
# The chain (all steps generated): one theorem Ctttt `checkStep` per step t < n from its ranges, then `chain`.
if [ "$(awk '{print $1}' "$run/steps.txt" | sort -un | wc -l)" = "$n" ]; then
  V=$(grep -v '^#' "$tables/table-1.txt" | tail -1 | cut -d' ' -f1)
  {
    printf 'import Robbins.Cert.SO.EvalKChain\nimport Robbins.Cert.SO.LanesSound\n'
    [ "$WN" -gt 0 ] && printf 'import Robbins.Cert.SO.LanesWinSound\n'
    awk -v ns="$ns" '{print "import " ns ".Step." $4}' "$run/steps.txt"
    printf '\n/-! The chain of the run %s: the step checks from their ranges (generated by code/formal-proof/gen.sh). -/\n\n' "$name"
    printf 'namespace %s\n\nopen Robbins.Cert.SO.K Robbins.Cert.SO.L\n\nset_option maxRecDepth 100000\n' "$ns"
    awk -v n="$n" -v wn="$WN" '
      function p4(x) { return sprintf("%04d", x) }
      function flush(   a, b, i, acc, cs, hiT) {
        if (cur == "") return
        a = p4(cur); b = p4(cur + 1)
        printf "\ntheorem C%s : checkStep grid %d Data.T%s Data.T%s = true :=\n", a, cur, b, a
        if (kind == "tops" && wn > 0) {
          cs = "["
          for (i = 0; i < k; i++)
            cs = cs (i > 0 ? ", " : "") (kd[i] == "win" ? "LPart.win " lo[i] " " hi[i] " " ww[i] : "LPart.rng " lo[i] " " hi[i])
          cs = cs "]"
          printf "  checkStep_of_lanesParts grid %d Data.T%s Data.T%s\n    %s\n    (by decide +kernel)\n", cur, b, a, cs
          printf "    fun i hi => match i, hi with\n"
          for (i = 0; i < k; i++) printf "    | %d, _ => %s\n", i, mod[i]
          printf "    | _ + %d, hi => absurd hi (by simp)\n", k
        } else if (kind == "tops") {
          cs = "["; for (i = 0; i < k; i++) cs = cs lo[i] ", "; cs = cs hi[k - 1] "]"
          printf "  checkStep_of_lanesRanges grid %d Data.T%s Data.T%s %s rfl (by decide +kernel)\n", cur, b, a, cs
          printf "    fun i hi => match i, hi with\n"
          for (i = 0; i < k; i++) printf "    | %d, _ => %s\n", i, mod[i]
          printf "    | _ + %d, hi => absurd hi (by simp)\n", k
        } else {
          acc = mod[0]
          for (i = 1; i < k; i++) {
            hiT = (i == k - 1) ? "Data.T" a ".length" : hi[i]
            acc = sprintf("(checkRange_join grid %d Data.T%s Data.T%s 0 %s (%s) %s %s)", cur, b, a, lo[i], hiT, acc, mod[i])
          }
          printf "  checkStep_of_checkRange grid %d Data.T%s Data.T%s %s\n", cur, b, a, acc
        }
        cur = ""
      }
      $1 == n { next }
      $1 != cur { flush(); cur = $1; k = 0; kind = ($5 == "tops" || $5 == "win") ? "tops" : "lits" }
      { lo[k] = $2; hi[k] = $3; mod[k] = $4; kd[k] = $5; ww[k] = $6; k++ }
      END {
        flush()
        printf "\ntheorem chain : ChainSO grid 1\n    ["
        for (t = 1; t <= n; t++) printf "%sData.T%s", (t > 1 ? ", " : ""), p4(t)
        printf "] :=\n  "
        for (t = 1; t < n; t++) printf "chainSO_cons C%s (", p4(t)
        printf "chainSO_last S%s", p4(n)
        for (t = 1; t < n; t++) printf ")"
        printf "\n"
      }' "$run/steps.txt"
    printf '\nend %s\n' "$ns"
  } | put "$run/Chain.lean"
  put "$run/Final.lean" <<EOT
import Robbins.Cert.SO.RunMain
import $ns.Chain

/-! The bound of the run $name: \`uh_1 (cnt_1, ..., cnt_1) = $V\` (generated by code/formal-proof/gen.sh). -/

namespace $ns

open Robbins.Cert Robbins.Cert.SO.K

theorem grid_ok : Robbins.Cert.SO.ok DS grid = true := by
  decide +kernel

theorem value : uhOf $((m - 1)) Data.T0001 (fun _ => grid.cnt 1) = $V := by
  decide +kernel

/-- \`v $n ≥ $V / 2 ^ 36\`. -/
theorem le_v : (($V : ℕ) : ℝ) / DS ≤ Robbins.v $n := by
  have h := le_v_of_chainSO grid grid_ok $((m - 1)) (by norm_num) rfl _ chain
  rwa [show grid.n = $n from rfl, List.getD_cons_zero, value] at h

/-- A relaxed sub-solution of value \`$V / 2 ^ 36\` at time \`1\` and the memory \`(1, ..., 1)\`. -/
theorem relaxed : ∃ u : Robbins.RelaxedSubSolution $n $m, u.u 1 (fun _ => 1) = (($V : ℕ) : ℝ) / DS := by
  have h := relaxed_of_chainSO grid grid_ok $((m - 1)) (by norm_num) rfl _ chain
  rwa [show grid.n = $n from rfl, List.getD_cons_zero, value] at h

end $ns
EOT
  echo "chain: $run/Chain.lean, $run/Final.lean (value $V)"
fi
echo "generated $run: n = $n, m = $m, $(wc -l < "$run/steps.txt") step modules"
