// Packs the tables written by soq (code/soq, option emit=T:FILE) into a Lean module for the
// kernel check of Robbins/Cert/SO/EvalK.lean: the grid, the claimed table `Nn` of time T + 1 and
// `Nt` of time T. A table is a list of literals of up to 16 states, the state s in the bits
// [W s, W (s + 1)), W = 48 (m + 1), under a leading 1 bit; a state holds uh in the bits [0, 48) and
// sg_l in the bits [48 (l + 1), 48 (l + 2)).
// Usage: robbins-so-pack EMIT.txt NAMESPACE OUT.lean
//        robbins-so-pack grid GRID.txt NAMESPACE OUT.lean          (soq emitall: the grid module)
//        robbins-so-pack table TABLE.txt M NAMESPACE NAME OUT.lean (soq emitall: the table `NAME` of one time)
use std::fmt::Write as _;
use std::io::{BufRead, BufReader, Write};

fn table(lines: &mut impl Iterator<Item = String>, m: usize) -> Vec<Vec<u64>> {
    let cnt: usize = lines.next().unwrap().trim().parse().unwrap();
    (0..cnt)
        .map(|_| {
            let v: Vec<u64> = lines.next().unwrap().split_whitespace().map(|x| x.parse().unwrap()).collect();
            assert_eq!(v.len(), m + 1);
            for &x in &v {
                assert!(x < 1u64 << 48, "field of 48 bits or more");
            }
            v
        })
        .collect()
}

fn literals(t: &[Vec<u64>], m: usize) -> Vec<String> {
    t.chunks(16)
        .map(|ch| {
            let mut s = String::from("0x1");
            for st in ch.iter().rev() {
                for f in (0..=m).rev() {
                    let v = if f == 0 { st[0] } else { st[f] };
                    write!(s, "{:012x}", v).unwrap();
                }
            }
            s
        })
        .collect()
}

fn emit_list(out: &mut String, name: &str, lits: &[String]) {
    let chunks: Vec<&[String]> = lits.chunks(256).collect();
    for (i, ch) in chunks.iter().enumerate() {
        writeln!(out, "def {}_{} : List Nat := [\n{}]\n", name, i, ch.join(",\n")).unwrap();
    }
    let names: Vec<String> = (0..chunks.len()).map(|i| format!("{}_{}", name, i)).collect();
    writeln!(out, "noncomputable def {} : List Nat := Robbins.Cert.K.lflat [{}]\n", name, names.join(", ")).unwrap();
}

fn main() {
    let a: Vec<String> = std::env::args().collect();
    if a.len() > 1 && a[1] == "grid" {
        return grid_module(&a[2..]);
    }
    if a.len() > 1 && a[1] == "table" {
        return table_module(&a[2..]);
    }
    assert_eq!(a.len(), 4, "usage: robbins-so-pack EMIT.txt NAMESPACE OUT.lean");
    let f = BufReader::new(std::fs::File::open(&a[1]).unwrap());
    let mut lines = f.lines().map(|l| l.unwrap()).filter(|l| !l.starts_with('#'));
    let h: Vec<usize> = lines.next().unwrap().split_whitespace().map(|x| x.parse().unwrap()).collect();
    let (n, m, sh, k, j, t) = (h[0], h[1], h[2], h[3], h[4], h[5]);
    assert_eq!(sh, 36);
    let gpt: Vec<String> = lines.next().unwrap().split_whitespace().map(|x| x.to_string()).collect();
    let start: Vec<String> = lines.next().unwrap().split_whitespace().map(|x| x.to_string()).collect();
    assert_eq!(gpt.len(), j);
    assert_eq!(start.len(), n);
    let tn = table(&mut lines, m);
    let tt = table(&mut lines, m);
    let mut out = String::new();
    writeln!(out, "-- Generated by code/so-pack from {}, do not edit.", std::path::Path::new(&a[1]).file_name().unwrap().to_string_lossy()).unwrap();
    writeln!(out, "import Robbins.Cert.EvalK\n\nnamespace {}\n", a[2]).unwrap();
    writeln!(out, "def grid : Robbins.Cert.Grid := ⟨{}, {}, {}, [{}],\n  [{}]⟩\n", n, m, k, gpt.join(", "), start.join(", ")).unwrap();
    writeln!(out, "def t : Nat := {}\n", t).unwrap();
    emit_list(&mut out, "Nn", &literals(&tn, m));
    emit_list(&mut out, "Nt", &literals(&tt, m));
    writeln!(out, "end {}", a[2]).unwrap();
    std::fs::File::create(&a[3]).unwrap().write_all(out.as_bytes()).unwrap();
    println!("n={} m={} K={} J={} T={} states {} and {}", n, m, k, j, t, tn.len(), tt.len());
}

fn header(src: &str) -> String {
    format!("-- Generated by code/so-pack from {}, do not edit.\n", std::path::Path::new(src).file_name().unwrap().to_string_lossy())
}

// grid GRID.txt NAMESPACE OUT.lean: `def grid` from the grid file of soq emitall (n m SH K J, gpt, start).
fn grid_module(a: &[String]) {
    assert_eq!(a.len(), 3, "usage: robbins-so-pack grid GRID.txt NAMESPACE OUT.lean");
    let f = BufReader::new(std::fs::File::open(&a[0]).unwrap());
    let mut lines = f.lines().map(|l| l.unwrap()).filter(|l| !l.starts_with('#'));
    let h: Vec<usize> = lines.next().unwrap().split_whitespace().map(|x| x.parse().unwrap()).collect();
    let (n, m, sh, k, j) = (h[0], h[1], h[2], h[3], h[4]);
    assert_eq!(sh, 36);
    let gpt: Vec<String> = lines.next().unwrap().split_whitespace().map(|x| x.to_string()).collect();
    let start: Vec<String> = lines.next().unwrap().split_whitespace().map(|x| x.to_string()).collect();
    assert_eq!(gpt.len(), j);
    assert_eq!(start.len(), n);
    let mut out = header(&a[0]);
    writeln!(out, "import Robbins.Cert.Grid\n\nnamespace {}\n", a[1]).unwrap();
    writeln!(out, "/-- The grid of the run. -/\ndef grid : Robbins.Cert.Grid := ⟨{}, {}, {}, [{}],\n  [{}]⟩\n", n, m, k, gpt.join(", "), start.join(", ")).unwrap();
    writeln!(out, "end {}", a[1]).unwrap();
    std::fs::File::create(&a[2]).unwrap().write_all(out.as_bytes()).unwrap();
    println!("grid n={} m={} K={} J={}", n, m, k, j);
}

// table TABLE.txt M NAMESPACE NAME OUT.lean: the table of one time of soq emitall as `NAME : List Nat`.
fn table_module(a: &[String]) {
    assert_eq!(a.len(), 5, "usage: robbins-so-pack table TABLE.txt M NAMESPACE NAME OUT.lean");
    let m: usize = a[1].parse().unwrap();
    let f = BufReader::new(std::fs::File::open(&a[0]).unwrap());
    let mut lines = f.lines().map(|l| l.unwrap()).filter(|l| !l.starts_with('#'));
    let tb = table(&mut lines, m);
    assert!(lines.next().is_none(), "trailing lines");
    let mut out = header(&a[0]);
    writeln!(out, "import Robbins.Cert.EvalK\n\nnamespace {}\n", a[2]).unwrap();
    emit_list(&mut out, &a[3], &literals(&tb, m));
    writeln!(out, "end {}", a[2]).unwrap();
    std::fs::File::create(&a[4]).unwrap().write_all(out.as_bytes()).unwrap();
    println!("table {} states {}", a[3], tb.len());
}
