import Mathlib

/-! A second formalization of the problem, written separately from the statement of the problem alone (stopping times for the filtration of the values), verbatim but for this comment, the namespace `Indep` and the `end` that closes its `noncomputable section`. Written with auto-bound implicits. -/

namespace Indep

open MeasureTheory
open Set
open ENNReal

noncomputable section

/-!
# Robbins' Problem: Formalization of the Full-Information Expected Rank Problem

We formalize the problem where X_1, ..., X_n are i.i.d. uniform on [0,1].
A stopping rule τ stops at some time 1 ≤ τ ≤ n based on the observed values.
The loss is the rank of the selected value (rank 1 = smallest).
v(n) is the minimal expected rank over all stopping rules.
-/

-- 1. The probability space

/-- Lebesgue measure restricted to [0,1], a probability measure on ℝ. -/
abbrev unitMeasure : Measure ℝ :=
  MeasureTheory.volume.restrict (Set.Icc (0 : ℝ) 1)

instance : IsProbabilityMeasure unitMeasure := by
  refine ⟨?h⟩
  dsimp [unitMeasure]
  rw [Measure.restrict_apply MeasurableSet.univ]
  rw [Set.univ_inter]
  rw [Real.volume_Icc]
  simp

/-- The sample space Ω_n = [0,1]^n with product measure. -/
@[reducible]
def Ω (n : ℕ) : Type := Fin n → ℝ

instance (n : ℕ) : MeasurableSpace (Ω n) := inferInstanceAs (MeasurableSpace (Fin n → ℝ))

/-- The probability measure on Ω_n (product of n copies of unitMeasure). -/
def P (n : ℕ) : Measure (Ω n) :=
  Measure.pi (fun (_ : Fin n) => unitMeasure)

instance (n : ℕ) : IsProbabilityMeasure (P n) := by
  unfold P
  infer_instance

/-- The i-th random variable X_i : Ω_n → ℝ, the i-th coordinate. -/
def X (n : ℕ) (i : Fin n) : Ω n → ℝ := fun ω => ω i

lemma X_measurable (n : ℕ) (i : Fin n) : Measurable (X n i) := by
  -- X n i is definitionally fun ω => ω i
  exact measurable_pi_apply i

-- 2. The filtration

/-- The σ-algebra generated by the first k coordinates (k ≤ n). -/
@[instance_reducible]
def filtration (n k : ℕ) (hk : k ≤ n) : MeasurableSpace (Ω n) :=
  MeasurableSpace.comap (fun ω i => ω (Fin.castLE hk i)) inferInstance

-- 3. Stopping rules

/-- A stopping rule is a measurable function τ : Ω_n → Fin n
    (representing the selected time, where 0 = first observation, n-1 = last observation)
    such that for all t : Fin n, the event {τ ≤ t} is in the σ-algebra generated by X_0,...,X_t. -/
structure StoppingRule (n : ℕ) where
  τ : Ω n → Fin n
  measurable_τ : Measurable τ
  stopping_time : ∀ (t : Fin n),
    @MeasurableSet (Ω n) (filtration n (t.val + 1) (by
      have h := t.is_lt
      omega)) {ω | (τ ω).val ≤ t.val}

-- 4. The rank

/-- The rank of a value x among a finite set of values (1 = smallest). -/
def rankValue (x : ℝ) (values : Finset ℝ) : ℕ :=
  1 + (values.filter (fun y => y < x)).card

/-- The rank of the selected value X_τ(ω) among all X_i(ω). -/
def selectedRank (n : ℕ) (τ : StoppingRule n) (ω : Ω n) : ℕ :=
  let i := τ.τ ω
  rankValue (X n i ω) (Finset.image (fun (j : Fin n) => X n j ω) Finset.univ)

-- 5. Expected rank

/-- The expected rank for a stopping rule. -/
def expectedRank (n : ℕ) (τ : StoppingRule n) : ℝ :=
  ∫ ω, (selectedRank n τ ω : ℝ) ∂(P n)

-- 6. Optimal value

/-- A constant stopping rule: always stop at time 1 (i.e., select the first observation).
    Requires n ≥ 1. -/
def alwaysStop1 (n : ℕ) [NeZero n] : StoppingRule n where
  τ := fun _ => 0
  measurable_τ := by
    exact measurable_const
  stopping_time := by
    intro t
    have : {ω : Ω n | ((0 : Fin n).val : ℕ) ≤ (t : ℕ)} = Set.univ := by
      ext ω; simp
    rw [this]
    exact MeasurableSet.univ

/-- The set of expected ranks is nonempty (there is at least one stopping rule).
    Requires n ≥ 1. -/
theorem expectedRank_nonempty (n : ℕ) [NeZero n] :
    {r : ℝ | ∃ (τ : StoppingRule n), expectedRank n τ = r}.Nonempty := by
  refine ⟨expectedRank n (alwaysStop1 n), ?_⟩
  exact ⟨alwaysStop1 n, rfl⟩

/-- The rank is always at least 1. -/
theorem selectedRank_ge_one (n : ℕ) (τ : StoppingRule n) (ω : Ω n) :
    1 ≤ (selectedRank n τ ω : ℝ) := by
  dsimp [selectedRank, rankValue]
  have : (1 : ℕ) ≤ 1 + (Finset.filter (fun y => y < X n (τ.τ ω) ω)
    (Finset.image (fun (j : Fin n) => X n j ω) Finset.univ)).card := by
    omega
  exact_mod_cast this

/-- The optimal value v(n) = inf over all stopping rules of the expected rank. -/
def robbinsValue (n : ℕ) : ℝ :=
  sInf {r : ℝ | ∃ (τ : StoppingRule n), expectedRank n τ = r}

end

end Indep
