#!/usr/bin/env bash
# Writes the table "From the paper to the proof" of STATEMENTS.md from paper/main.tex, with the numbers of
# paper/main.aux (build the paper first). Each numbered statement, and each section that carries one, has next to its
# \label two macros that print nothing:
#   \lean{A, B, ...}      its Lean declarations, full names; the first is the one its proof names;
#   \computed{p, q, ...}  scripts and recorded outputs, paths from the root of the repository.
# A statement with no \lean is "not formalized" in the table. Checks: every declaration is declared in Robbins/
# (namespaces followed; a structure field counts; not Robbins/Challenge.lean, which repeats the statements), every
# path exists, every \decl{N} of the text sits in a proof and is the first entry of the \lean macro of the statement
# it proves, and the first entry of every theorem, lemma, proposition and corollary is named by a \decl. Exits 1 if a
# check fails, and with --check also if STATEMENTS.md differs. The axioms of the declarations are checked by CI
# (code/formal-proof/main_axioms.lean).
# Run from anywhere: paper/statement_map.sh [--check]
set -euo pipefail
cd "$(dirname "$0")/.."
tex=paper/main.tex aux=paper/main.aux out=STATEMENTS.md
begin='<!-- statement-map: generated by paper/statement_map.sh from paper/main.tex, do not edit -->'
end='<!-- end statement-map -->'
[[ -f $aux ]] || { echo "no $aux: build the paper first" >&2; exit 1; }
t=$(mktemp -d); trap 'rm -rf "$t"' EXIT
fail=0

# Every declaration of the Lean package (not the two Comparator files, which repeat the statement): full
# name, file, line.
find Robbins -name '*.lean' ! -path Robbins/Challenge.lean | LC_ALL=C sort | while read -r f; do
  awk -v file="$f" '
    /^[[:space:]]*namespace / { ns[++d] = $2; next }
    /^[[:space:]]*end [A-Za-z]/ { if (d > 0 && ns[d] == $2) d--; else if (d > 0) { n = split(ns[d], p, "."); if (p[n] == $2) d-- } next }
    function prefix(  s, i) { s = ""; for (i = 1; i <= d; i++) s = s ns[i] "."; return s }
    st != "" && /^[^[:space:]]/ { st = "" }
    st != "" && match($0, /^  [A-Za-z_][A-Za-z0-9_'"'"']* :/) {
      split(substr($0, 3, RLENGTH - 2), w, /[[:space:]:]+/); print st "." w[1] "\t" file "\t" NR; next
    }
    {
      line = $0; sub(/^(@\[[^]]*\][[:space:]]*)?((private|protected|noncomputable|nonrec|unsafe|partial)[[:space:]]+)*/, "", line)
      if (match(line, /^(theorem|lemma|def|abbrev|structure|inductive|instance|class|opaque|axiom)[[:space:]]+[^[:space:]:({]+/)) {
        split(substr(line, 1, RLENGTH), w, /[[:space:]]+/)
        print prefix() w[2] "\t" file "\t" NR
        st = (w[1] == "structure" || w[1] == "class") ? prefix() w[2] : ""
      }
    }' "$f"
done > "$t/index.tsv"

# The source without its comments (an unescaped % to the end of the line).
sed -E 's/(^|[^\\])%.*$/\1/' "$tex" > "$t/body.tex"

# Statement numbers.
sed -n 's/^\\newlabel{\([^}]*\)}{{\([^}]*\)}.*/\1\t\2/p' "$aux" > "$t/numbers.tsv"

# One row per numbered statement, and per section with a macro: kind, label, \lean list, \computed list,
# \leanwait text.
awk '
  function arg(m,   s) { if (!match($0, "\\\\" m "\\{[^}]*\\}")) return ""; s = substr($0, RSTART + length(m) + 2, RLENGTH - length(m) - 3); gsub(/[[:space:]]+/, "", s); return s }
  function warg(   s) { if (!match($0, /\\leanwait\{[^}]*\}/)) return ""; return substr($0, RSTART + 10, RLENGTH - 11) }
  /\\begin\{(theorem|lemma|proposition|corollary|conjecture|remark|claim)\}/ {
    match($0, /\\begin\{[a-z]+\}/); kind = substr($0, RSTART + 7, RLENGTH - 8)
    if (!match($0, /\\label\{[^}]*\}/)) { print "unlabelled " kind " at line " NR > "/dev/stderr"; bad = 1; next }
    print kind US substr($0, RSTART + 7, RLENGTH - 8) US arg("lean") US arg("computed") US warg(); next
  }
  /\\(sub)*section\*?\{/ && /\\(lean|computed|leanwait)\{/ {
    match($0, /\\label\{[^}]*\}/); print "section" US substr($0, RSTART + 7, RLENGTH - 8) US arg("lean") US arg("computed") US warg()
  }
  END { exit bad }' US=$'\x1f' "$t/body.tex" > "$t/rows.tsv" || fail=1

sed -n '/^\\begin{document}/,$p' "$t/body.tex" | grep -o '\\decl{[^}]*}' | sed 's/^\\decl{\(.*\)}$/\1/' | sort > "$t/named.txt" || true

# Checks on the names.
awk -F$'\x1f' '$3 != "" { split($3, a, ","); print a[1] }' "$t/rows.tsv" | sort > "$t/firsts.txt"
while read -r n; do grep -qxF "$n" "$t/firsts.txt" || { echo "FAIL \\decl{$n} is not the first entry of a \\lean macro" >&2; fail=1; }; done < "$t/named.txt"
dup=$(uniq -d "$t/named.txt"); [[ -z $dup ]] || { echo "FAIL named by more than one \\decl: $dup" >&2; fail=1; }
while IFS=$'\x1f' read -r kind label lean comp wait; do
  case $kind in theorem|lemma|proposition|corollary)
    [[ -n $lean ]] || continue
    grep -qxF "${lean%%,*}" "$t/named.txt" || { echo "FAIL $kind $label: its proof does not name ${lean%%,*}" >&2; fail=1; } ;;
  esac
done < "$t/rows.tsv"
# Each \decl sits in a proof, and names the first entry of the \lean macro of the statement it proves: the
# statement just before, or the one of "\begin{proof}[Proof of ...\ref{label}]".
sed -n '/^\\begin{document}/,$p' "$t/body.tex" | awk '
  function arg(m,   s) { if (!match($0, "\\\\" m "\\{[^}]*\\}")) return ""; s = substr($0, RSTART + length(m) + 2, RLENGTH - length(m) - 3); gsub(/[[:space:]]+/, "", s); return s }
  /\\begin\{(theorem|lemma|proposition|corollary|conjecture|remark|claim)\}/ && match($0, /\\label\{[^}]*\}/) {
    cur = substr($0, RSTART + 7, RLENGTH - 8); s = arg("lean"); sub(/,.*/, "", s); first[cur] = s
  }
  /\\begin\{proof\}/ { inproof = 1; target = cur; if (match($0, /^\\begin\{proof\}\[[^]]*\\ref\{[^}]*\}/)) { s = substr($0, RSTART, RLENGTH); sub(/.*\\ref\{/, "", s); sub(/\}$/, "", s); target = s } }
  function decls(line, inp,   n) {
    while (match(line, /\\decl\{[^}]*\}/)) {
      n = substr(line, RSTART + 6, RLENGTH - 7); line = substr(line, RSTART + RLENGTH)
      if (!inp) { print "FAIL \\decl{" n "} outside a proof"; bad = 1 }
      else if (first[target] != n) { print "FAIL \\decl{" n "} in the proof of " target ", whose first \\lean entry is " (first[target] == "" ? "none" : first[target]); bad = 1 }
    }
  }
  match($0, /\\end\{proof\}/) { decls(substr($0, 1, RSTART - 1), inproof); inproof = 0; decls(substr($0, RSTART + RLENGTH), 0); next }
  { decls($0, inproof) }
  END { exit bad }' >&2 || fail=1


# The table.
{
  echo "$begin"
  echo
  echo '<!-- prettier-ignore-start -->'
  echo
  printf '%s\x1f%s\x1f%s\n' Paper 'Lean declarations (in bold, the one its proof names)' 'Scripts and recorded outputs' > "$t/cells"
  while IFS=$'\x1f' read -r kind label lean comp wait; do
    num=$(awk -F'\t' -v l="$label" '$1 == l { print $2; exit }' "$t/numbers.tsv")
    [[ -n $num ]] || { echo "FAIL $label has no number in $aux" >&2; fail=1; }
    name="${kind^} $num"
    cells=()
    if [[ -n $lean ]]; then
      IFS=, read -ra ds <<< "$lean"
      for n in "${ds[@]}"; do
        hit=$(awk -F'\t' -v n="$n" '$1 == n { print $2 "#L" $3; exit }' "$t/index.tsv")
        if [[ -z $hit ]]; then
          echo "FAIL $name: $n is not declared in Robbins/" >&2; fail=1; c="\`$n\`"
        else
          c="[\`$n\`]($hit)"
        fi; [[ $n == "${ds[0]}" ]] && grep -qxF "$n" "$t/named.txt" && c="**$c**"
        cells+=("$c")
      done
    fi
    [[ -n $wait ]] && { echo "FAIL $name: \\leanwait{$wait}" >&2; fail=1; }
    leancell=$(IFS=$'\x1e'; echo "${cells[*]:-}" | sed $'s/\x1e/, /g')
    [[ -z $lean && -z $wait && $kind != section ]] && leancell="not formalized"

    compcell=""
    if [[ -n $comp ]]; then
      IFS=, read -ra ps <<< "$comp"
      for p in "${ps[@]}"; do
        [[ -e $p ]] || { echo "FAIL $name: $p does not exist" >&2; fail=1; }
        compcell+="${compcell:+, }[\`$p\`]($p)"
      done
    fi
    printf '%s\x1f%s\x1f%s\n' "$name" "$leancell" "$compcell" >> "$t/cells"
  done < "$t/rows.tsv"
  # Each column padded to its widest cell, the form mdformat gives the table.
  awk -F'\x1f' '
    { for (i = 1; i <= 3; i++) { c[NR, i] = $i; if (length($i) > w[i]) w[i] = length($i) } }
    function row(r,   i, l) { l = "|"; for (i = 1; i <= 3; i++) l = l sprintf(" %-" w[i] "s |", c[r, i]); return l }
    END {
      print row(1)
      l = "|"; for (i = 1; i <= 3; i++) { d = ""; while (length(d) < w[i]) d = d "-"; l = l " " d " |" } print l
      for (r = 2; r <= NR; r++) print row(r)
    }' "$t/cells"
  echo
  echo '<!-- prettier-ignore-end -->'
  echo
  echo "$end"
} > "$t/table.md"
[[ $fail == 0 ]] || { echo "statement map: FAIL" >&2; exit 1; }

# Into STATEMENTS.md, between the markers.
grep -qxF "$begin" "$out" && grep -qxF "$end" "$out" || { echo "no statement-map markers in $out" >&2; exit 1; }
awk -v b="$begin" -v e="$end" -v tf="$t/table.md" '
  $0 == b { while ((getline l < tf) > 0) print l; skip = 1; next }
  $0 == e { skip = 0; next }
  !skip { print }' "$out" > "$t/out.md"
if [[ ${1:-} == --check ]]; then
  diff -q "$t/out.md" "$out" > /dev/null || { echo "statement map: $out is not up to date" >&2; exit 1; }
else
  cp "$t/out.md" "$out"
fi
echo "statement map: $(( $(wc -l < "$t/rows.tsv") )) rows, $(awk -F$'\x1f' '$3 != "" { n += split($3, a, ",") } END { print n + 0 }' "$t/rows.tsv") Lean names, $(wc -l < "$t/named.txt") named in proofs: ok"
